DROP TABLE IF EXISTS calculator;

CREATE TABLE calculator (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    parameter1 INT NOT NULL,
    parameter2 INT NOT NULL,
    result DOUBLE NOT NULL,
    operation VARCHAR(255) NOT NULL
);

CREATE SEQUENCE calculator_seq START WITH 1 INCREMENT BY 1;
